param(
  [string]$Stage1Root = "",
  [string]$TrashRoot = "",
  [switch]$KeepConfig = $true,
  [switch]$GenerateEmptyRegionConfig = $true,
  [switch]$PrintNextSteps = $true
)

$ErrorActionPreference = "Stop"

function New-Timestamp {
  return (Get-Date -Format "yyyyMMdd_HHmmss")
}

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Force -Path $Path | Out-Null
  }
}

function Move-IfExists([string]$Source, [string]$DestDir) {
  if (Test-Path -LiteralPath $Source) {
    Ensure-Dir $DestDir
    Move-Item -Force -LiteralPath $Source -Destination $DestDir
  }
}

# Resolve Stage1Root default: the folder containing this script
if ([string]::IsNullOrWhiteSpace($Stage1Root)) {
  $Stage1Root = Split-Path -Parent $MyInvocation.MyCommand.Path
}
$Stage1Root = (Resolve-Path -LiteralPath $Stage1Root).Path

if (-not (Test-Path -LiteralPath $Stage1Root)) {
  throw "Stage1Root not found: $Stage1Root"
}

# Default TrashRoot: <project_root>/trash_stage1
if ([string]::IsNullOrWhiteSpace($TrashRoot)) {
  $projectRoot = Split-Path -Parent $Stage1Root
  $TrashRoot = Join-Path $projectRoot "trash_stage1"
}

Ensure-Dir $TrashRoot

$ts = New-Timestamp
$trash = Join-Path $TrashRoot $ts
Ensure-Dir $trash

Write-Host "Cleaning Stage1 outputs..." -ForegroundColor Cyan
Write-Host "  Stage1Root: $Stage1Root"
Write-Host "  TrashDir : $trash" -ForegroundColor Yellow

# 1) stage1/simulation_data: move everything except config.json (optional)
$sim = Join-Path $Stage1Root "simulation_data"
if (Test-Path -LiteralPath $sim) {
  $simDest = Join-Path $trash "simulation_data"
  Ensure-Dir $simDest

  Get-ChildItem -LiteralPath $sim -Force | ForEach-Object {
    if ($KeepConfig -and $_.Name -eq "config.json") {
      return
    }
    Move-Item -Force -LiteralPath $_.FullName -Destination $simDest
  }
}

# 2) __pycache__ folders (top-level + core)
Move-IfExists (Join-Path $Stage1Root "__pycache__") (Join-Path $trash "__pycache__")
Move-IfExists (Join-Path $Stage1Root "core\__pycache__") (Join-Path $trash "core")

# 3) workflow_figures (generated)
Move-IfExists (Join-Path $Stage1Root "workflow_figures") (Join-Path $trash "workflow_figures")

# 4) legacy internal recycle bins (if any)
Move-IfExists (Join-Path $Stage1Root "_recycle_bin") (Join-Path $trash "_recycle_bin")

Write-Host "Done." -ForegroundColor Green
Write-Host "Trash saved to: $trash" -ForegroundColor Green

# 5) Generate a minimal empty region_config.json for copy-friendly repos
if ($GenerateEmptyRegionConfig) {
  $regionCfg = Join-Path $Stage1Root "simulation_data\region_config.json"
  if (-not (Test-Path -LiteralPath (Split-Path -Parent $regionCfg))) {
    Ensure-Dir (Split-Path -Parent $regionCfg)
  }

  if (-not (Test-Path -LiteralPath $regionCfg)) {
    $obj = [ordered]@{
      created_at = (Get-Date).ToString("s")
      note = "Empty placeholder generated by clean_outputs.ps1; run --action split_regions to populate."
      regions = @{}
    }
    ($obj | ConvertTo-Json -Depth 10) | Out-File -FilePath $regionCfg -Encoding utf8
    Write-Host "Generated empty region_config.json: $regionCfg" -ForegroundColor Green
  }
}

# 6) Print recommended next steps
if ($PrintNextSteps) {
  $py = "python"
  $entry = Join-Path $Stage1Root "main_pdms_svr_bandscan_full.py"
  $tmmCsv = Join-Path $Stage1Root "simulation_data\tmm_emissivity_data.csv"
  $regionCfg = Join-Path $Stage1Root "simulation_data\region_config.json"

  Write-Host "" 
  Write-Host "Next steps (CLI actions):" -ForegroundColor Cyan
  if (-not (Test-Path -LiteralPath $tmmCsv)) {
    Write-Host "  1) Generate TMM data:  $py $entry --action simulate" -ForegroundColor Yellow
  } else {
    Write-Host "  1) TMM data exists:    $tmmCsv" -ForegroundColor DarkGray
  }

  if (-not (Test-Path -LiteralPath $regionCfg)) {
    Write-Host "  2) Create regions:     $py $entry --action split_regions" -ForegroundColor Yellow
  } else {
    Write-Host "  2) Create regions:     $py $entry --action split_regions" -ForegroundColor Yellow
  }
  Write-Host "  3) Run region sim:     $py $entry --action region_simulation" -ForegroundColor Yellow
  Write-Host "  4) Train region SVR:   $py $entry --action train_regions" -ForegroundColor Yellow
  Write-Host "  5) Inspect status:     $py $entry --action inspect_regions" -ForegroundColor Yellow
  Write-Host "" 
  Write-Host "Tip: if you prefer global (non-region) workflow: --action full_pipeline" -ForegroundColor DarkGray
}
