from __future__ import annotations

DEFAULTS = {
    "use_random_search": True,
    "C_values": [100, 500, 1000],
    "gamma_values": [0.1, 0.5, 1.0],
    "epsilon_values": [0.01],
    "random_search_iter": 10,
    "use_param_distributions": True,
    "cv_folds": 2,
    "test_size": 0.3,
    "pdms_sample": 2,
    "sio2_sample": 2,
    "lambda_step": 0.02,
    "lambda_min": 2.0,
    "lambda_max": 14.0,
    "thickness_step": 10.0,
    "min_thickness_nm": 100.0,
    "max_thickness": 1000.0,
    "sio2_thicknesses_nm": [500, 1500, 2500],
    "n_jobs": -1,
    "joblib_backend": "threading",
    "energy_tol": 1e-3,
    "strict_energy_check": True,
    "random_seed": 42,
    "external_extrapolation": True,
    "extrap_train_thickness_min": 100,
    "extrap_train_thickness_max": 700,
    "extrap_test_thickness_min": 750,
    "extrap_test_thickness_max": 1000,
    "scale_y": False,
    "min_required_samples": 1974,
    "enforce_min_samples": True,
    "group_split_by_thickness": True,
    "allow_random_split": False,
    "train_mlp_baseline": False,
    "feature_engineering": True,
    "use_interaction_features": True,
    "n_pdms_eff": 1.41,
    "n_sio2_eff": 1.46,
    "use_bayesian_opt": False,
    "n_trials": 50,
    "optuna_timeout_s": None,
    "optuna_n_jobs": 1,
    "optuna_cv_n_jobs": 1,
    "optuna_max_samples": 60000,
    "optuna_verbose": True,
    "substrate_n_real": 3.42,
    "substrate_n_imag": 0.0,
    "allow_placeholder_substrate": False,
    "assume_opaque_substrate": False,
    "prioritize_atmospheric_window": True,
    "region_split_strategy": "lambda_only",
    "overlap_ratio": 0.05,
    "region_overlap_ratio": 0.05,
    "min_wl_span_um": 1e-3,
    "min_th_span_nm": 1.0,
    "wl_distance_weight": 1.0,
    "th_distance_weight": 1.0,
    "region_weight_temperature": 1.0,
    "in_range_weight_boost": 1.5,
    "min_region_weight": 1e-6,
    "energy_check_n_points": 500,
    "extrapolation_n_samples": 1000,
    "extrapolation_tmm_max_points": 200,
    "max_samples_per_region": 250000,
    "tmm_baseline_time_s": 12.3,
    "avg_time_per_region": 30,
    "enable_tmm_cache": True,
    "cache_ttl_s": 180.0,
    "cache_maxsize": 60000,
    "cache_lambda_quant_um": 1e-4,
    "cache_thickness_quant_nm": 0.1,
    "batch_size": 100,
    "early_stopping_rounds": 2,
    "use_halton_search": True,
    "halton_scramble": True,
    "halton_max_samples": 20000,
    "halton_verbose": False,
    "search_use_subset": True,
    "search_max_samples": 3000,
    "trial_timeout_s": 45,
    "search_timeout_s": 240,
    "limit_lambda_range": True,
    "resample_uniform_grid": True,
    "material_grid_step": 0.02,

        # Baseline metadata (paper / reporting). These are used to document the
        # reference conditions for the configured TMM baseline time.
        "tmm_baseline_wavelength_points": 500,
        "tmm_baseline_hardware": "Intel Core i9-10900K",
    "scan_soft_cap": 400,
    "scan_hard_cap": 1500,
    "scan_max_train_samples": 12000,
    "scan_save_predictions": False,
    "scan_prompt_save_predictions": True,
    # Region training artifacts (default OFF to keep stage1 copyable/clean).
    # When enabled, each region saves a small y_test/y_pred file under region_models/<region>/.
    "region_save_predictions": False,
    "region_predictions_format": "csv",  # csv|json
    "region_edge_eps": 1e-6,
    "enable_ellipsometry": False,
    "ellipsometry_file": "ellipsometry_data.xlsx",
    "ellipsometry_angle_deg": 70.0,
    "ellipsometry_n0": 1.0,
    "ellipsometry_apply_to_material": "none",
    "model_version": "svr-v1",
    "enable_experiment_tracking": False,
    "experiment_tracking_uri": "",
    "experiment_name": "pdms_emissivity",
    "use_gpu_tmm": False,
    "gpu_backend": "auto",
}
